# Generated by Django 4.2.11 on 2024-04-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='地址ID')),
                ('customer_address', models.CharField(max_length=20, verbose_name='联系人地址')),
                ('customer_company', models.CharField(max_length=20, verbose_name='公司名称')),
                ('customer_job', models.CharField(max_length=20, verbose_name='联系人职业')),
                ('customer_city', models.CharField(max_length=20, verbose_name='城市')),
                ('customer_area', models.IntegerField(choices=[(0, '华北'), (1, '东北'), (2, '华东'), (3, '华西'), (4, '华中'), (5, '华南'), (6, '西南'), (7, '西北')], default=1, null=True, verbose_name='地区')),
                ('customer_postalcode', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('customer_fax', models.CharField(max_length=20, verbose_name='传真')),
                ('customer_country', models.CharField(max_length=20, verbose_name='国家')),
            ],
            options={
                'verbose_name': '地址信息',
                'verbose_name_plural': '地址信息',
                'db_table': 'Address',
                'ordering': ['address_id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='客户ID')),
                ('customer_name', models.CharField(max_length=20, verbose_name='联系人姓名')),
                ('customer_password', models.CharField(max_length=20, verbose_name='客户密码')),
                ('customer_tel', models.CharField(max_length=20, verbose_name='客户电话')),
                ('customer_status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='客户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.address', verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'Customer',
                'ordering': ['customer_id'],
            },
        ),
    ]
