# Generated by Django 4.2.11 on 2024-04-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('supplier', '0001_initial'),
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('order_orderdate', models.DateTimeField(null=True, verbose_name='订购日期')),
                ('order_senddate', models.DateTimeField(blank=True, null=True, verbose_name='发货日期')),
                ('order_receivedate', models.DateTimeField(blank=True, null=True, verbose_name='到货日期')),
                ('order_confirmdate', models.DateTimeField(blank=True, null=True, verbose_name='货款确认日期')),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='订单价格')),
                ('order_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='运费')),
                ('order_C_name', models.CharField(max_length=80, null=True, verbose_name='货主名称')),
                ('order_C_Address', models.CharField(max_length=120, null=True, verbose_name='货主地址')),
                ('order_C_City', models.CharField(max_length=30, null=True, verbose_name='货主城市')),
                ('order_C_Area', models.IntegerField(choices=[(0, '华北'), (1, '东北'), (2, '华东'), (3, '华西'), (4, '华中'), (5, '华南'), (6, '西南'), (7, '西北')], default=1, null=True, verbose_name='地区')),
                ('order_C_PostalCode', models.CharField(max_length=20, null=True, verbose_name='货主邮政编码')),
                ('order_C_Country', models.CharField(max_length=30, null=True, verbose_name='货主国家')),
                ('order_Payway', models.CharField(blank=True, max_length=20, null=True, verbose_name='支付方式')),
                ('order_Insurance', models.IntegerField(choices=[(0, '不使用保险'), (1, '使用保险')], default=1, null=True, verbose_name='保险信息')),
                ('order_carrier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier.carrier', verbose_name='运货商ID')),
                ('order_customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='客户ID')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'Order',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='产品ID')),
                ('product_name', models.CharField(max_length=80, null=True, verbose_name='产品名称')),
                ('product_quantity', models.CharField(max_length=40, null=True, verbose_name='单位数量')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='单价')),
                ('product_photo', models.ImageField(null=True, upload_to='images/product', verbose_name='商品照片')),
                ('product_inventory', models.SmallIntegerField(null=True, verbose_name='库存量')),
                ('product_orderquantity', models.SmallIntegerField(null=True, verbose_name='订购量')),
                ('product_reorderquanatity', models.SmallIntegerField(null=True, verbose_name='再订购量')),
                ('product_status', models.IntegerField(choices=[(0, '中止'), (1, '在售')], null=True, verbose_name='状态')),
                ('product_detail', models.TextField(null=True, verbose_name='商品描述')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.category', verbose_name='类别ID')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'product',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_weight', models.SmallIntegerField(null=True, verbose_name='重量')),
                ('od_quantity', models.SmallIntegerField(null=True, verbose_name='数量')),
                ('od_notes', models.TextField(null=True, verbose_name='备注')),
                ('od_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.order', verbose_name='订单ID')),
                ('od_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='产品ID')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'OrderDetail',
                'ordering': ['od_id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='产品ID'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_productbarch_id', models.IntegerField(verbose_name='产品批次ID')),
                ('info_productiondate', models.DateTimeField(null=True, verbose_name='生产日期')),
                ('info_expirationdate', models.DateTimeField(null=True, verbose_name='保质期')),
                ('info_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='类别ID')),
            ],
            options={
                'verbose_name': '生产信息',
                'verbose_name_plural': '生产信息',
                'db_table': 'Information',
                'unique_together': {('info_productbarch_id', 'info_product_id')},
            },
        ),
    ]
