# Generated by Django 5.0.4 on 2024-04-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_information_info_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_charge",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="运费"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_price",
            field=models.CharField(max_length=255, null=True, verbose_name="订单价格"),
        ),
    ]
