# Generated by Django 4.2.11 on 2024-04-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='供应商ID')),
                ('supplier_company', models.CharField(max_length=80, null=True, verbose_name='公司名称')),
                ('supplier_name', models.CharField(max_length=60, null=True, verbose_name='联系人姓名')),
                ('supplier_job', models.CharField(max_length=60, null=True, verbose_name='联系人职务')),
                ('supplier_address', models.CharField(max_length=120, null=True, verbose_name='地址')),
                ('supplier_city', models.CharField(max_length=30, null=True, verbose_name='城市')),
                ('supplier_area', models.CharField(max_length=30, null=True, verbose_name='地区')),
                ('supplier_postalcode', models.CharField(max_length=20, null=True, verbose_name='邮政编码')),
                ('supplier_country', models.CharField(max_length=30, null=True, verbose_name='国家')),
                ('supplier_tel', models.CharField(max_length=48, null=True, verbose_name='电话')),
                ('supplier_fax', models.CharField(blank=True, max_length=48, null=True, verbose_name='传真')),
                ('supplier_homepage', models.ImageField(blank=True, null=True, upload_to='images/supplier', verbose_name='主页照片')),
                ('supplier_status', models.IntegerField(choices=[(0, '歇业中'), (1, '营业中')], null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
                'db_table': 'Supplier',
                'ordering': ['supplier_id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='类别ID')),
                ('category_name', models.CharField(max_length=30, null=True, verbose_name='类别名称')),
                ('category_notes', models.TextField(null=True, verbose_name='类别说明')),
                ('category_photo', models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='图片')),
                ('category_inittime', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('category_updatetime', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '商品类别信息',
                'verbose_name_plural': '商品类别信息',
                'db_table': 'Category',
                'ordering': ['category_id'],
            },
        ),
    ]
