# Generated by Django 5.0.4 on 2024-04-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=255, null=True, verbose_name="类别名称"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_address",
            field=models.CharField(max_length=255, null=True, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_area",
            field=models.CharField(max_length=255, null=True, verbose_name="地区"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_city",
            field=models.CharField(max_length=255, null=True, verbose_name="城市"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_company",
            field=models.CharField(max_length=255, null=True, verbose_name="公司名称"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_country",
            field=models.CharField(max_length=255, null=True, verbose_name="国家"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_fax",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="传真"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_job",
            field=models.CharField(max_length=255, null=True, verbose_name="联系人职务"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_name",
            field=models.CharField(max_length=255, null=True, verbose_name="联系人姓名"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_postalcode",
            field=models.CharField(max_length=255, null=True, verbose_name="邮政编码"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_tel",
            field=models.CharField(max_length=255, null=True, verbose_name="电话"),
        ),
    ]
